export const data = [
  {
    id: "1",
    name: "Sarah Johnson",
    role: "Admin",
    status: "Active",
    joinDate: "2024-01-15",
    department: "Finance",
  },
  {
    id: "2",
    name: "Michael Chen",
    role: "User",
    status: "Active",
    joinDate: "2024-02-20",
    department: "Engineer",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    role: "Manager",
    status: "Inactive",
    joinDate: "2024-01-08",
    department: "Arts",
  },
  {
    id: "4",
    name: "David Thompson",
    role: "User",
    status: "Pending",
    joinDate: "2024-03-10",
    department: "Finance",
  },
  {
    id: "5",
    name: "Jessica Wilson",
    role: "Admin",
    status: "Active",
    joinDate: "2024-01-25",
    department: "Engineer",
  },
  {
    id: "6",
    name: "Robert Kumar",
    role: "User",
    status: "Active",
    joinDate: "2024-02-14",
    department: "Finance",
  },
  {
    id: "7",
    name: "Lisa Anderson",
    role: "Manager",
    status: "Active",
    joinDate: "2024-03-05",
    department: "Arts",
  },
  {
    id: "8",
    name: "James Martinez",
    role: "Guest",
    status: "Inactive",
    joinDate: "2024-02-28",
    department: "Arts",
  },
  {
    id: "9",
    name: "Amanda Taylor",
    role: "User",
    status: "Active",
    joinDate: "2024-03-15",
    department: "Engineer",
  },
  {
    id: "10",
    name: "Christopher Lee",
    role: "Admin",
    status: "Pending",
    joinDate: "2024-03-20",
    department: "Finance",
  },
  {
    id: "11",
    name: "Maria Garcia",
    role: "User",
    status: "Active",
    joinDate: "2024-01-30",
    department: "Arts",
  },
  {
    id: "12",
    name: "Kevin Brown",
    role: "Manager",
    status: "Active",
    joinDate: "2024-02-10",
    department: "Engineer",
  },
  {
    id: "13",
    name: "Rachel Davis",
    role: "User",
    status: "Inactive",
    joinDate: "2024-01-12",
    department: "Finance",
  },
  {
    id: "14",
    name: "Daniel Miller",
    role: "Guest",
    status: "Active",
    joinDate: "2024-03-08",
    department: "Arts",
  },
  {
    id: "15",
    name: "Nicole White",
    role: "Admin",
    status: "Active",
    joinDate: "2024-02-25",
    department: "Engineer",
  },
  {
    id: "16",
    name: "Andrew Jackson",
    role: "User",
    status: "Pending",
    joinDate: "2024-03-18",
    department: "Finance",
  },
  {
    id: "17",
    name: "Stephanie Clark",
    role: "Manager",
    status: "Active",
    joinDate: "2024-01-20",
    department: "Finance",
  },
  {
    id: "18",
    name: "Gregory Lewis",
    role: "User",
    status: "Active",
    joinDate: "2024-02-15",
    department: "Engineer",
  },
  {
    id: "19",
    name: "Michelle Walker",
    role: "Guest",
    status: "Inactive",
    joinDate: "2024-03-12",
    department: "Arts",
  },
  {
    id: "20",
    name: "Timothy Hall",
    role: "Admin",
    status: "Active",
    joinDate: "2024-01-28",
    department: "Finance",
  },
];
